### ISSUE TITLE
The directionality of dependency arrows is shown backwards

### ISSUE THREAD

**Issue by CodeGnome** [snasirca/mikado-graph-generator#1]
In a directed graph like Mikado, the graph should flow from the root node towards the leaves. So, the arrows should point to the dependencies rather than towards the goal, although the order of eventual refactorings will flow in the opposite direction. So, the directionality of dependencies should look more like the following:

![Mikado Graph](https://user-images.githubusercontent.com/385462/34261144-3a5ece1a-e636-11e7-83b1-7e00f106b4b1.png)

Currently, the #depends_on method shows an inverted relationship, and the README provides no documented way to change the directionality.

**Comment by snasirca** [comment]
Thanks @CodeGnome for reporting this. I wasn't aware how a Mikado graph is supposed to be directed. I was conveying the flow of refactorings with the current `#depends_on` implementation. I can add an option to the generator to toggle the directionality.

I'm curious to know where you learned about this convention. Do you have a reference you can share with me?

**Comment by CodeGnome** [comment]
@snasirca A Mikado graph is a directed graph, and ideally acyclic. [_The Mikado Method_](https://www.manning.com/books/the-mikado-method) states that [the direction flows from the goal towards the dependencies](https://livebook.manning.com#!/book/the-mikado-method/chapter-3/point-946-71-71-0):

> The dependency arrows point from the original goal toward its prerequisites (see figure 3.1)...
>
> ![Figure 3.1](https://dpzbhybb2pdcj.cloudfront.net/ellnestam/Figures/03fig01.jpg)

Because the Mikado Method starts at the root of the tree, the graph's flow is root-to-leaves rather than leaves-to-root as you build the tree because _you're diagramming dependencies as they are discovered_ rather than mapping the order of execution. While it may seem counterintuitive to read the flow this way, the arrows are saying: "A depends on B or C" rather than "B and C lead to A."

Does that help?

**Comment by snasirca** [comment]
@CodeGnome I've pushed a fix for this issue. Let me know if this is helpful. Feedback is welcome.
