### ISSUE TITLE
build failing on TravisCI; dependabot "recommended" by Travis

### ISSUE THREAD

**Issue by todd-a-jacobs** [snasirca/mikado-graph-generator#60]
The failing build can probably be fixed just by updating the RuboCop offense, or moving the item to `.rubocop_todo.yml`. However, Travis is also suggesting moving to GitHub's native Dependabot, and the question of whether TravisCI or GitHub Actions are a better long-term option are worth discussing.

If the repository owner can add [Dependabot](https://github.com/dependabot) to the project, I can provide a PR that fixes the RuboCop error that's causing Travis to fail. Meanwhile, I'd also like to know if refactoring to GitHub Actions instead of TravisCI for testing is worthwhile or desirable for the project. It's more work to refactor than to fix, but seems like it could be useful and fun to do.

**Comment by snasirca** [comment]
@todd-a-jacobs thanks for bringing this to my attention. I think I fixed the Rubocop issue. Can you give me some feedback if something is still not right? I thought I was already using the native dependabot.

> Meanwhile, I'd also like to know if refactoring to GitHub Actions instead of TravisCI for testing is worthwhile or desirable for the project. It's more work to refactor than to fix, but seems like it could be useful and fun to do.

I switched over to GitHub Actions. Let me know if you see any issues with that. When I originally setup this repo, Actions weren't a thing. But I've been using them over the last couple of years and like it a lot more. I agree with you that this is a more useful direction.
